// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZYGygJud-MIGjMQ2d-W69L3PFlgAb3-s',
    appId: '1:259593261281:web:43127ca7f729aa704a27a0',
    messagingSenderId: '259593261281',
    projectId: 'clothesorder-10e15',
    authDomain: 'clothesorder-10e15.firebaseapp.com',
    storageBucket: 'clothesorder-10e15.firebasestorage.app',
    measurementId: 'G-WTC55BHN4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSedABHayDAObSeCwWzvILGp2QUE61wAA',
    appId: '1:259593261281:android:b30dae6c327c89fe4a27a0',
    messagingSenderId: '259593261281',
    projectId: 'clothesorder-10e15',
    storageBucket: 'clothesorder-10e15.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZYGygJud-MIGjMQ2d-W69L3PFlgAb3-s',
    appId: '1:259593261281:web:58a9c7b9e14cb96b4a27a0',
    messagingSenderId: '259593261281',
    projectId: 'clothesorder-10e15',
    authDomain: 'clothesorder-10e15.firebaseapp.com',
    storageBucket: 'clothesorder-10e15.firebasestorage.app',
    measurementId: 'G-VM8JWWH9W8',
  );
}
